name: tiktok_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  http: ^1.3.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.1.2
  timeago: ^3.7.0
  video_compress: ^3.1.3
  video_player: ^2.9.2
  path_provider: ^2.0.15
  path: ^1.8.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png